# Generated by Django 5.0.2 on 2024-09-18 08:43

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_homepagecarouselimages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepagecarouselimages',
            name='page',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='carousel_images', to='home.homepage'),
        ),
    ]
